Revision 1.2
sisoputnfrba/hilolay pull request #1
Opened 2019-10-15 19:38 UTC by tferraro

- Semaforos!
- Agregado hilolay_close para forzar el cierre del hilo principal 😄

2019-10-15 19:54 UTC, MaximilianoFelice requested changes

2019-10-15 19:54 UTC, MaximilianoFelice commented on hilolay.h
> +	int hilolay_wait(char *sem_name);
-1 a trabajar con semáforos con nombres. Utilicemos una interfaz similar a pthread: http://profesores.elo.utfsm.cl/~agv/elo330/2s06/lectures/POSIX_threads/POSIX_Threads_Synchronization.html.

2019-10-15 19:54 UTC, MaximilianoFelice commented on hilolay.h
> +	int hilolay_close(void);
Tenemos que hacer realmente el close? No podemos simplemente wrappearlo o hacer un `hilolay_return`?

2019-10-15 19:54 UTC, MaximilianoFelice commented on hilolay_alumnos.h
> +		int (*suse_wait) (int, char *);
Mismo tema que el de la interfaz alli arriba. Usar char* y similares nos obliga a manejar memoria dinámica y no esta cheto.

2019-10-15 19:54 UTC, MaximilianoFelice commented on hilolay_internal.c
> +    if(sem_not_adquired) {
Por qué estamos haciendo esto? Se supone que luego de una syscall (en este caso el `wait`) deberíamos siempre llamar a replanificar.

2019-10-19 18:08 UTC, tferraro commented on hilolay.h
> +	int hilolay_close(void);
- No podemos wrappearlo, porque hay que wrappear el `return 0;` del hilo principal, algo que no podemos porque ya se está ejecutando. Hay funciones locas de gcc, pero es demasiada magia.
- `hilolay_return` será, no me calienta el nombre 😛

2019-10-19 19:06 UTC, tferraro commented on hilolay.h
> +	int hilolay_wait(char *sem_name);
Acá había un issue, nosotros en SUSE estamos guardando los semaforos bajo su nombre, por lo que en realidad tener una estructura similar a `sem_t` solo va a tener el nombre adentro.
Lo hablamos con Adro y Esteban y tiene un comportamiento muuuuuy parecido a los `named semaphores`, así que básicamente en vez de usar la interfaz de poxis o el viejo sem_init, nos robamos la de los semaforos con nombre:

http://man7.org/linux/man-pages/man3/sem_open.3.html
http://man7.org/linux/man-pages/man3/sem_close.3.html

Son lo mismo, pero le pasás el nombre al inicializarlo 😉

2019-10-20 15:47 UTC, tferraro commented on hilolay_internal.c
> +    if(sem_not_adquired) {
True tht

2019-10-20 15:47 UTC, tferraro commented on hilolay_alumnos.h
> +		int (*suse_wait) (int, char *);
See above, so below

2019-10-21 02:52 UTC, MaximilianoFelice approved these changes

2019-10-21 12:29 UTC, merged